### PR TITLE
Make `docs/index.md` a symlink.

### PR DESCRIPTION
**Pull request by real-yfprojects**
* docs/index.md : Symlink to `README.md`

* .pre_commit_helper_scripts/copy_readme.py : Delete file.

* .pre-commit-config.yaml : Remove hook calling above script.

### CODE REVIEW

**Comment by jsh9** [comment]
Thank you @real-yfprojects !

**Comment by jsh9** [comment]
Hi @real-yfprojects :

Page building failed after I merged this PR.  Here's the console log: https://github.com/jsh9/pydoclint/actions/runs/5641666077/job/15280085518

Do you know what this error is about?  Thanks!

**Comment by real-yfprojects** [comment]
Wow, it seems like jekyll doesn't support symlinks.

**Comment by jsh9** [comment]
I see - thanks!  I guess the only way to fix it is to revert the commit then.

**Comment by jsh9** [comment]
Reverted: 1531feab8441c045e76aac3798bd38af57b8c699

**Pull request merged**
